version: "3.7"

services:

  shopsweb:
    build: ./shopsweb
    container_name: shopsweb
    restart: always
    environment:
      - APP_NAME=NearbyShops
    expose:
      - 8080
    volumes:
      - $PWD/logs:/app/logs
    depends_on:
      - shopsdb

  shopsnginx:
    build: ./shopsnginx
    container_name: shopsnginx
    restart: always
    ports:
      - "8083:80"
    volumes:
      - $PWD/nginx_logs:/var/log/nginx

  shopsdb:
    image: postgres:12.0-alpine
    container_name: shopsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:               